# Generated by Django 4.1 on 2022-09-06 04:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Create_Studentmodel', models.DateTimeField(verbose_name=datetime.date.today)),
                ('Student_Name', models.CharField(max_length=20)),
                ('Student_Rollno', models.IntegerField()),
                ('Student_Depatment', models.CharField(max_length=30)),
                ('Is_Student_Id_delete', models.BooleanField(default=False)),
            ],
        ),
    ]
